; Proyecto: Grifo de cerveza automatizado (ESP32 + RFID + Supabase)
; Etapa 1 — Blink: confirma toolchain, driver CP2102 y flasheo.

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
